# Generated by Django 4.2.4 on 2023-11-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOcorrencias',
            fields=[
                ('nro_bop', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_manutencao', models.DateTimeField(auto_now=True)),
                ('apresentacao', models.BooleanField()),
                ('enquadramento', models.CharField(max_length=200)),
                ('fato_relevante', models.BooleanField()),
                ('genero_suspeito', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=10)),
                ('id_operacao', models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.CASCADE, related_name='id_operacao_pc_ocor', to='mainApp.modeloperacoes')),
                ('id_relator', models.ForeignKey(db_column='id_relator', on_delete=django.db.models.deletion.CASCADE, related_name='id_relator', to='mainApp.modelpessoas')),
                ('id_suspeito', models.ForeignKey(db_column='id_suspeito', on_delete=django.db.models.deletion.CASCADE, related_name='id_suspeito', to='mainApp.modelpessoas')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_pc_ocor', to='mainApp.modelusuarios')),
            ],
            options={
                'db_table': 'pc_ocorrencias',
            },
        ),
        migrations.CreateModel(
            name='ModelProcedimento',
            fields=[
                ('nro_procedimento', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_manutencao', models.DateTimeField(auto_now=True)),
                ('apresentacao', models.BooleanField()),
                ('enquadramento', models.CharField(max_length=200)),
                ('fato_relevante', models.BooleanField()),
                ('genero_autor', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=10)),
                ('id_apresentante', models.ForeignKey(db_column='id_apresentante', on_delete=django.db.models.deletion.CASCADE, to='mainApp.modelpessoas')),
                ('id_autor', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.CASCADE, related_name='id_autor_pc', to='mainApp.modelpessoas')),
                ('id_operacao', models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.CASCADE, related_name='id_operacao_pc_proced', to='mainApp.modeloperacoes')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_pc_proced', to='mainApp.modelusuarios')),
                ('nro_bop', models.ForeignKey(db_column='nro_bop', on_delete=django.db.models.deletion.CASCADE, to='pc.modelocorrencias')),
            ],
            options={
                'db_table': 'pc_procedimentos',
            },
        ),
        migrations.CreateModel(
            name='ModelCumprimentoMedidas',
            fields=[
                ('nro_registro', models.AutoField(primary_key=True, serialize=False)),
                ('processo', models.CharField(max_length=100)),
                ('enquadramento', models.CharField(max_length=200)),
                ('instituicao', models.CharField(choices=[('PM', 'PM'), ('PC', 'PC'), ('PC/PM', 'PC/PM')], max_length=10)),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_manutencao', models.DateTimeField(auto_now=True)),
                ('fato_relevante', models.BooleanField()),
                ('id_operacao', models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.CASCADE, related_name='id_operacao_pc_cump', to='mainApp.modeloperacoes')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_pc_cump', to='mainApp.modelusuarios')),
            ],
            options={
                'db_table': 'pc_cumprimento_medidas',
            },
        ),
        migrations.CreateModel(
            name='ModelApreensao',
            fields=[
                ('nro_registro', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200)),
                ('tipo_objeto', models.CharField(choices=[('DOCUMENTO', 'DOCUMENTO'), ('CELULAR', 'CELULAR'), ('OUTRO', 'OUTRO OBJETO'), ('ARMA', 'ARMA'), ('MUNICAO', 'MUNICAO'), ('DROGA', 'DROGA'), ('RECURSO_NATURAL', 'RECURSO NATURAL'), ('PARTES_DO_CORPO', 'PARTES DO CORPO'), ('VEICULO', 'VEICULO')], max_length=200)),
                ('tipo_droga', models.CharField(choices=[('ANFETAMINA', 'ANFETAMINA'), ('COCAINA', 'COCAINA'), ('CRACK', 'CRACK'), ('ECSTASY', 'ECSTASY'), ('MACONHA', 'MACONHA'), ('MDMA', 'MDMA'), ('MERLA', 'MERLA'), ('NOBESIO', 'NOBESIO'), ('OXI', 'OXI')], max_length=200)),
                ('qtd_droga', models.FloatField()),
                ('und_medida', models.CharField(choices=[('Kg', 'QUILOGRAMA'), ('g', 'GRAMAS'), ('UND', 'UNIDADE'), ('L', 'LITROS')], max_length=200)),
                ('tipo_arma', models.CharField(choices=[('ARMA_DE_FOGO', 'ARMA DE FOGO'), ('ARMA_BRANCA', 'ARMA BRANCA'), ('SIMULACRO', 'SIMULACRO')], max_length=200)),
                ('especie_arma', models.CharField(max_length=50)),
                ('qtd_arma', models.IntegerField()),
                ('municao', models.IntegerField()),
                ('imei1_celular', models.CharField(max_length=50)),
                ('imei2_celular', models.CharField(max_length=50)),
                ('outros_objetos', models.CharField(max_length=200)),
                ('qtd_outros_objetos', models.IntegerField()),
                ('placa_veiculo', models.CharField(max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_manutencao', models.DateTimeField(auto_now=True)),
                ('fato_relevante', models.BooleanField()),
                ('id_operacao', models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.CASCADE, related_name='id_operacao_pc_apre', to='mainApp.modeloperacoes')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_pc_apre', to='mainApp.modelusuarios')),
            ],
            options={
                'db_table': 'pc_apreensao',
            },
        ),
    ]
