# Generated by Django 4.2.4 on 2023-11-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcumprimentomedidas',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='modelocorrencias',
            name='genero_suspeito',
        ),
        migrations.RemoveField(
            model_name='modelprocedimento',
            name='genero_autor',
        ),
    ]
